### ISSUE TITLE
[SDK Binding - Cosmos] Finish implementation of Cosmos Converter

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#1371]
Continue implementation of CosmosConverter started in the following PR:

- #1109

### Tasks

- [ ] Reopen PR 1109 and rebase to pull in the latest changes
- [ ] Test converter E2E with latest Cosmos WebJobs Ext changes
- [ ] Write unit tests for the converter
