### ISSUE TITLE
[SDK-Bindings - Queue] Design for enabling Queue trigger bindings

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#1422]
We'd like to have dotnet-isolated parity with in-proc for Queue bindings. As output bindings are still out of scope,and technically input does not exist, we would like to focus on enabling trigger binding scenarios.

Here is what is missing from in-proc:

- [QueueMessage](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Queues/src/Models/QueueMessage.cs)

**Notes:**

1. We may not need to use deferred binding for all of these scenarios
2. We will want to avoid the all or nothing approach for enabling these scenarios and focus on one at a time

**Todo:**

- [x] Create a design document outlining the approach we want to take for Queue trigger binding in dotnet-isolated
    - Must outline approach for the missing types listed above
    - Must also discuss if we want to enable input bindings for Queues or not
    - Must include constraints and outline scope of work that needs to happen to make the implementation possible
- [x] Implement initial prototype for `QueueMessage` 
- [x] Create new issues for the remaining work that needs to happen

**Comment by liliankasem** [comment]
Design document checked in to Antares Docs repo; prototype implemented; remaining work issues created.

- [Prototype branch](https://github.com/Azure/azure-functions-dotnet-worker/tree/liliankasem/queue-message-binding)
