### ISSUE TITLE
Update samples for Retry Policy

### ISSUE THREAD

**Issue by satvu** [Azure/azure-functions-dotnet-worker#1448]
Update sample apps to use retry policies correctly as defined [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=fixed-delay%2Cin-process&pivots=programming-language-csharp#retries). 

**Tasks**
- [x] Remove example attributes from [FunctionApp](https://github.com/Azure/azure-functions-dotnet-worker/tree/main/samples/FunctionApp) placed on incorrect trigger types.
- [x] Update [Extensions sample app](https://github.com/Azure/azure-functions-dotnet-worker/tree/main/samples/Extensions) to use latest extension packages with retry policies available.
- [x] Add example usage of the two retry attributes to relevant functions (Timer, Kafka, EH, Cosmos)
