### ISSUE TITLE
[SDK-Bindings - Tables] Implement deferred binding support in WebJobs extension 

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#1473]
### Problem Statement

Update the [Tables WebJobs extension](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/tables/Microsoft.Azure.WebJobs.Extensions.Tables) to support binding to ParameterBindingData for input bindings.

### Tasks

- [x] Investigate the Tables WebJobs extension project and figure out where changes need to be made to enable binding to `ParameterBindingData`
- [x] Implement changes needed to support input binding to `ParameterBindingData`
- [x] Write unit test for this new code path

### Definition of Done

1. Tables WebJobs extension changes made to support `ParameterBindingData` and PR is merged

**Comment by liliankasem** [comment]
Use the extension author guide to help you make these changes:

- [Extension author guide](https://dev.azure.com/msazure/One/_git/AAPT-Antares-Docs?path=/TeamDocs/FunctionTeamDocs/EngineeringHowTos/DeferredBinding/DeferredBindingExtensionGuide.md&version=GBmaster&_a=preview)
