### ISSUE TITLE
[SDK-Bindings - Tables] Implement converter in Tables worker extension to support TableClient +

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#1474]
#### Problem Statement

Implement `TablesConverter` to enable binding to the `TableClient`, `TableEntity` and `IEnumerable<TableEntity>` types so that we have parity with in-proc.

- [Tables worker extension project](https://github.com/Azure/azure-functions-dotnet-worker/tree/feature/sdk-type-binding/extensions/Worker.Extensions.Tables/src)

#### Tasks

- [x] Implement converter that enables binding to a single `TableClient`, `TableEntity` and multiple `TableEntity`'s
    - Being able to bind to multiple table entities looks like this: `IEnumerable<TableEntity>`, `IAsyncCollector<TableEntity>`*
- [x] Implement managed identity support via Options and AzureComponentFactory
- [x] Write unit tests for converter
- [x] Write unit tests for any other classes implemented (such as the config and options classes)
- [x] Write E2E tests for:
    - Function with Tables input binding to `TableClient`
    - Function with Tables input binding to `TableEntity`
    - Function with Tables input binding to `IEnumerable<TableEntity>`

* We may not need to support `IAsyncCollector<TableEntity>` so start with all of the other types first and we can come back to this at the end

#### Definition of Done

1. Worker Tables extension package is released (as a preview package) with support for binding to a `TableClient`, `TableEntity`, and `IEnumerable<TableEntity>`
2. Unit & E2E tests written and checked-in
3. Microsoft documentation updated to detail support for the new SDK-bindings

**Comment by liliankasem** [comment]
First, utilize the author guide to implement this changes:

- [Dotnet extension author guide](https://dev.azure.com/msazure/One/_git/AAPT-Antares-Docs?path=/TeamDocs/FunctionTeamDocs/EngineeringHowTos/DeferredBinding/DotnetIsolatedExtensionGuide.md&version=GBmaster&_a=preview)

If you're stuck, use the Cosmos DB and Blob extensions as examples of how to do this; they both have converters implemented with managed identity support:

- [Blob worker extension](https://github.com/Azure/azure-functions-dotnet-worker/tree/feature/sdk-type-binding/extensions/Worker.Extensions.Storage.Blobs/src)
- [Cosmos worker extension(https://github.com/Azure/azure-functions-dotnet-worker/tree/feature/sdk-type-binding/extensions/Worker.Extensions.CosmosDB/src)
