### ISSUE TITLE
[SDK-Bindings - ServiceBus] Implement ServiceBus extension E2E tests

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#1561]
## Problem Statement

The service bus extension does not currently have any E2E tests written for it.

Today, it's not possible to test service bus E2E with our current test setup a there is no emulator for it; to get past that, we will need to implement a spin up/tear down infrastructure in our pipelines where we create the service bus resources needed for the test, run the test, then tear everything back down. 

Something to consider is that this might be a good opportunity for us to move all the extension to the azure sdk for net repo which already has a full E2E test infra setup for service bus

## Tasks

- [x] Make a decision on moving the extension to the sdk for net repo 
- [ ] If not moving:
    - [ ] Design and implement servicebus test infrastructure using azure pipelines (consider using bicep)
    - [ ] Write servicebus E2E tests

**Comment by liliankasem** [comment]
Closing in favour of moving the extensions to the `azure-sdk-for-net` repo
