### ISSUE TITLE
[SDK-Bindings - EventGrid] Implement deferred binding support in WebJobs extension 

### ISSUE THREAD

**Issue by aishwaryabh** [Azure/azure-functions-dotnet-worker#1564]
### Problem Statement

Update the EventGrid WebJobs extension to support binding to ParameterBindingData for input bindings.

### Tasks

- [ ] Investigate the EventGrid WebJobs extension project and figure out where changes need to be made to enable binding to `ParameterBindingData`
- [ ] Implement changes needed to support input binding to `ParameterBindingData`
- [ ] Write unit test for this new code path

### Definition of Done

1. EventGrid WebJobs extension changes made to support `ParameterBindingData` and PR is merged

**Comment by aishwaryabh** [comment]
Don't need this since EventGrid should already have the appropriate payloads necessary to directly implement converter
